json.id product.id
json.name product.name
json.is_discounted? product.is_discounted?
json.price product.price
json.tax product.tax
json.total product.total
json.image_url product.image_url
json.description product.description
json.created_at product.created_at
json.supplier_id  product.supplier_id